.\" BSD Zero Clause License
.\" Copyright (c) 2025 David M Crumpton david.m.crumpton [at] gmail [dot] com
.\" Permission to use, copy, modify, and/or distribute this software for any
.\" purpose with or without fee is hereby granted.
.\" THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES WITH
.\" REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY
.\" AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY SPECIAL, DIRECT,
.\" INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM
.\" LOSS OF USE, DATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR
.\" OTHER TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR
.\" PERFORMANCE OF THIS SOFTWARE.
.Dd $Mdocdate: June 27 2025 $
.Dt BUFFY 6
.Os
.Sh NAME
.Nm buffy
.Nd Buffy the flouride dispenser game
.Sh SYNOPSIS
.Nm
.Op Fl cvbf Ar file
.Op Fl -daggerset
.Op Fl -colorized
.Sh DESCRIPTION
For creature lovers,
.Nm
is a game of dental hygenic fun.
Use your randomly selected tool
on whatever creature happens your way to clean the fangs before
the flouride runs out.
.Pp
The game will choose a creature at random and a tool to clean the teeth.
The player
can choose simple tools or select from daggers for more powerful cleaning.
.Pp
The options are as follows:
.Bl -tag -width Ds
.It Fl c
specifies to use visual mode.  An extra c enables color mode
.It Fl v
prints version and exits
.It Fl b
specifies use login name for character name.
.It Fl f Ar file
specifies the name of the game save file to load.
.It Fl -daggerset
specifies to use a dagger for cleaning fangs
.It Fl -colorized
enables option c twice for curses with color
.El
.Sh GAMEPLAY
You will clean the fangs one at time rotating through all four.
After completing cleaning of four fangs, you may continue cleaning,
skip a fang, quit, or save and quit.
You must enter integer values for applying flouride.
.Pp
Your score is printed out at the end.
.Sh HISTORY
The
.Nm
game appeared on GitHub in July 2025.
.Sh AUTHORS
.An -nosplit
.An David M. Crumpton
.Sh BUGS
The game only saves in your home directory when asked to save, but can only
load the game
with option
.Fl f
and its option argument is a loadable file.